apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
        - name: reverse-proxy
          # image: yoongunwo/image_proxy:1.1
          # image: yoongunwo/nid_proxy:1.0 # 1
          # image: yoongunwo/nid_proxy_cpp:1.1 # 2
          image: yoongunwo/nid_proxy_py:1.0 # 2
          # image: yoongunwo/nid_proxy_openblas:1.0
          # image: yoongunwo/nid_proxy_rs:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TARGET_PORT
              value: '80' # main container port
            - name: PROXY_PORT
              value: '8080'
          securityContext:
            privileged: true
            capabilities:
              add:
                - ALL
          resources:
            requests:
              cpu: 1000m
              memory: "512Mi"
            limits:
              cpu: 1000m
          # command: ['/bin/sh', '-c', 'while true; do sleep 1000; done']

---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: test
spec:
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---

