apiVersion: apps/v1
kind: Deployment
metadata:
  name: clf-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clf-image
  template:
    metadata:
      labels:
        app: clf-image
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
        - name: reverse-proxy
          image: yoongunwo/image_proxy:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TARGET_PORT
              value: '80' # main container port
            - name: PROXY_PORT
              value: '8080'
          securityContext:
            privileged: true
            capabilities:
              add:
                - ALL
          volumeMounts:
            - name: model
              mountPath: /app/model
          # command: ['/bin/sh', '-c', 'while true; do sleep 1000; done']
      volumes:
        - name: model
          hostPath:
            path: /home/yoon/model/my-app

---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
---

